### ISSUE TITLE
How to distribute newsletters?

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fortran-lang.github.io#10]
See #3 first.

How should we distribute the newsletter, and specifically, should we have a mailing list? 

Currently we have:

* Feed for RSS clients here: https://fortran-lang.org/news.xml
* Twitter: https://twitter.com/fortranlang, which we can further automate and have a GitHub bot post a tweet on a merged newsletter.

Regarding mailing lists, I've used Google Groups (not sure if still exists) and Mailchimp (great features but a PITA to work with).

Unless there's a really easy to set up and low maintenance mailing list solution, or we have a volunteer to do it, I'm not convinced that it's worthwhile doing this for the time being.

What do you think?

**Comment by certik** [comment]
For LFortran we use groups.io, i.e. https://groups.io/g/lfortran.

I agree Google Groups interface is really bad, especially if you do not use a gmail. 

The GitHub issues work almost like a mailinglist.

The other options to use are Zulip: https://lfortran.zulipchat.com, or Gitter: https://gitter.im/sympy/sympy. 

The advantage of a mailinglist is that you do not need to worry about closing an issue, so it's great for a general discussion or announcements. And you can use an email.

I wondered for LFortran a lot, whether we need a mailinglist or not, initially we just setup Zulip. But later we created a mailinglist, so that I can post my updates there, and we can have a general discussion from time to time if needed.

**Comment by milancurcic** [comment]
GitHub issues are great for developers with GitHub accounts and who want to follow everything about the development.

Zulip, Gitter, or Slack are good for development collaboration and building community, but they're not good for distributing newsletters and such.

So yes, for newsletters we need a low friction (just email signup) delivery like a mailing list. 

Twitter is better than mailing list for reaching people (non-subscribers can see it through the feed or retweets), but mailing list is better for discussion. 

However, would there be much discussion around news? It seems to me that the discussion would be centered more around a Chat (Zulip, Slack, etc.) or a Message Board (Discourse) format.

Groups.io seems simple and no-nonsense on first look. If you like it, we should try using it.

**Comment by certik** [comment]
If we decide to create a mailinglist, then groups.io is the best one I found.

The key question is:

>However, would there be much discussion around news? It seems to me that the discussion would be centered more around a Chat (Zulip, Slack, etc.) or a Message Board (Discourse) format.

That's what I didn't know initially either. The chat is less permanent, but the Discourse might be a good option. Discourse is probably the closest to a mailinglist.

The kind of discussions that people would have are visible e.g. here:

https://groups.google.com/forum/#!forum/comp.lang.fortran

You can see that anyone can post an announcement of a new project or a new idea or a new conference, and then people can discuss and comment. I think it's very helpful in this respect.

Essentially it would be *the* place to reach the Fortran community. Our CoC would apply to it, we would moderate it so that the discussions stay healthy.

**Comment by milancurcic** [comment]
We may be able to get a hosted Discourse instance for free: https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/

**Comment by LKedward** [comment]
I agree, I think Twitter makes the most sense as an easy way to distribute.
In terms of discussion it would be good to have a central moderated and modern place for Fortran.
(comp.lang.fortran is not moderated and I not too amenable for non-experts).
I don't have much experience with different discussion mediums - the free Discourse instance sounds like it's worth a try?

**Comment by milancurcic** [comment]
The mailing list is in place thanks to @certik, and is now listed on the landing page.

I also just applied for the free Discourse instance for open source projects. We should hear back about it in few days.

**Comment by milancurcic** [comment]
The Fortran Discourse instance is up: https://fortran-lang.discourse.group/

It's basically a self-managed, free instance of a modern message board.

Considering that in the meantime we also set up the mailing list, there's some overlap between the two as in that both facilitate discussion. Let's see how each works out and whether there's prevalent preference among the community for one or the other.

**Comment by LKedward** [comment]
Awesome, cheers for setting it up @milancurcic!

We have RSS and twitter for distributing newsletters and mailing list and discourse for discussions - is this issue now resolved?

**Comment by certik** [comment]
I think we can close it now. We have enough avenues now to have good solid engagement with the public and among ourselves and let's see how this goes and how we are using things. We might end up using both the mailinglist and the discourse.
