### ISSUE TITLE
Add Gemfile.lock to repo

### ISSUE THREAD

**Issue by LKedward** [fortran-lang/fortran-lang.github.io#17]
A minor point, and I will defer to those with more experience with Ruby, however my understanding is that for non-library projects (no dependents) the lock file should be committed to the repository so that all contributors are building within the same environment. Repo lock files are only then updated when updated dependencies have been tested.

**Comment by milancurcic** [comment]
My experience with Ruby is near zero, just enough to get by. What you say makes sense, Rust does [similarly](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries). 

This is most likely inconsequential because the site is built by GitHub, but I agree with committing Gemfile.lock to the repo.

**Comment by LKedward** [comment]
> This is most likely inconsequential because the site is built by GitHub...

This is actually an issue I think because the build is not strictly reproducible between the local copy and the GitHub build; so theoretically a local build could succeed but fail to build with GitHub when pushed.

I see now that this is [recommended for bundler](https://bundler.io/guides/faq.html#using-gemfiles-inside-gems) so I'll do a PR.

**Comment by milancurcic** [comment]
You're right, my bad. I see why it's important to have a Gemfile.lock now.
